version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:10.15
    steps:
      - checkout
      - run:
          name: install-npm
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: lint
          command: npm run lint
      - run:
          name: test
          command: npm test
      - run:
          name: build
          command: npm run build
